"""sync and commerce

Revision ID: 20260713_0002
Revises: 20260713_0001
Create Date: 2026-07-14 01:08:56.015990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260713_0002'
down_revision: Union[str, Sequence[str], None] = '20260713_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Composite provider ownership must exist before any new table references it.
    op.create_unique_constraint('uq_integration_connections_id_provider', 'integration_connections', ['id', 'provider'])
    op.create_table('integration_export_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('requester_session_digest', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.Enum('shops', 'products', 'skus', 'inventory', 'orders', 'order_items', 'refunds', 'shipments', 'settlements', 'daily_metrics', 'ad_accounts', 'ad_entities', 'ad_daily_metrics', 'ad_balance_snapshots', 'ad_finance_transactions', name='ck_integration_export_jobs_resource_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'ready', 'failed', 'expired', name='ck_integration_export_jobs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('relative_file_path', sa.String(length=2048), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("format IN ('csv', 'xlsx')", name='ck_integration_export_jobs_format'),
    sa.CheckConstraint('length(requester_session_digest) = 64', name='ck_integration_export_jobs_requester_digest_length'),
    sa.CheckConstraint('row_count >= 0', name='ck_integration_export_jobs_row_count_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id', name='uq_integration_export_jobs_public_id')
    )
    op.create_index('ix_integration_export_jobs_expires_at', 'integration_export_jobs', ['expires_at'], unique=False)
    op.create_index('ix_integration_export_jobs_requester_session_digest', 'integration_export_jobs', ['requester_session_digest'], unique=False)
    op.create_index('ix_integration_export_jobs_status', 'integration_export_jobs', ['status', 'created_at'], unique=False)
    op.create_table('integration_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.Enum('sync_resource', 'refresh_authorization', 'process_event', 'archive_cleanup', 'export', 'purge_connection', name='ck_integration_jobs_job_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'leased', 'running', 'retry_wait', 'succeeded', 'failed', 'cancelled', name='ck_integration_jobs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts >= 0 AND max_attempts > 0 AND attempts <= max_attempts', name='ck_integration_jobs_attempt_bounds'),
    sa.CheckConstraint('length(dedupe_key) = 64', name='ck_integration_jobs_dedupe_key_length'),
    sa.CheckConstraint('priority >= 0', name='ck_integration_jobs_priority_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_integration_jobs_dedupe_key')
    )
    op.create_index('ix_integration_jobs_claim', 'integration_jobs', ['status', 'available_at', 'priority', 'id'], unique=False)
    op.create_index('ix_integration_jobs_lease_expires_at', 'integration_jobs', ['lease_expires_at'], unique=False)
    op.create_table('integration_worker_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_job_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.CheckConstraint('active_job_count >= 0', name='ck_integration_worker_heartbeats_active_jobs_nonnegative'),
    sa.CheckConstraint('pid > 0', name='ck_integration_worker_heartbeats_pid_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', name='uq_integration_worker_heartbeats_worker_id')
    )
    op.create_index('ix_integration_worker_heartbeats_last_seen_at', 'integration_worker_heartbeats', ['last_seen_at'], unique=False)
    op.create_table('commerce_ad_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'active', 'inactive', 'closed', name='ck_commerce_ad_accounts_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_ad_accounts_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_ad_accounts_currency_format'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_ad_accounts_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_ad_account_id', name='uq_commerce_ad_accounts_connection_external_account')
    )
    op.create_index('ix_commerce_ad_accounts_status', 'commerce_ad_accounts', ['normalized_status'], unique=False)
    op.create_table('commerce_ad_balance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_ad_balance_snapshots_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_ad_balance_snapshots_currency_format'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_ad_balance_snapshots_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_ad_account_id', 'captured_at', name='uq_commerce_ad_balances_connection_account_captured')
    )
    op.create_index('ix_commerce_ad_balance_snapshots_captured_at', 'commerce_ad_balance_snapshots', ['captured_at'], unique=False)
    op.create_table('commerce_ad_daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Enum('account', 'campaign', 'ad_group', 'creative', 'material', name='ck_commerce_ad_daily_metrics_entity_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_entity_id', sa.String(length=255), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('granularity', sa.Enum('day', name='ck_commerce_ad_daily_metrics_granularity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('spend', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('attributed_sales', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cvr', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('roi', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('play_rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_ad_daily_metrics_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_ad_daily_metrics_currency_format'),
    sa.CheckConstraint('impressions >= 0 AND clicks >= 0 AND orders >= 0 AND (play_count IS NULL OR play_count >= 0)', name='ck_commerce_ad_daily_metrics_counts_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_ad_daily_metrics_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'entity_type', 'external_entity_id', 'stat_date', 'granularity', name='uq_commerce_ad_metrics_connection_entity_date_granularity')
    )
    op.create_index('ix_commerce_ad_daily_metrics_date', 'commerce_ad_daily_metrics', ['stat_date'], unique=False)
    op.create_table('commerce_ad_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Enum('account', 'campaign', 'ad_group', 'creative', 'material', name='ck_commerce_ad_entities_entity_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_entity_id', sa.String(length=255), nullable=False),
    sa.Column('external_parent_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'active', 'paused', 'ended', 'deleted', name='ck_commerce_ad_entities_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_ad_entities_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_ad_entities_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'entity_type', 'external_entity_id', name='uq_commerce_ad_entities_connection_type_external')
    )
    op.create_index('ix_commerce_ad_entities_parent', 'commerce_ad_entities', ['entity_type', 'external_parent_id'], unique=False)
    op.create_index('ix_commerce_ad_entities_status', 'commerce_ad_entities', ['normalized_status'], unique=False)
    op.create_table('commerce_ad_finance_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=False),
    sa.Column('external_ad_account_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'pending', 'completed', 'failed', 'reversed', name='ck_commerce_ad_finance_transactions_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_ad_finance_transactions_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_ad_finance_transactions_currency_format'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_ad_finance_transactions_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_transaction_id', name='uq_commerce_ad_finance_connection_external_transaction')
    )
    op.create_index('ix_commerce_ad_finance_transaction_at', 'commerce_ad_finance_transactions', ['transaction_at'], unique=False)
    op.create_table('commerce_daily_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('granularity', sa.Enum('day', name='ck_commerce_daily_metrics_granularity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('actual_sales', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('refund_count', sa.Integer(), nullable=False),
    sa.Column('visitor_count', sa.Integer(), nullable=False),
    sa.Column('buyer_count', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_daily_metrics_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_daily_metrics_currency_format'),
    sa.CheckConstraint('order_count >= 0 AND refund_count >= 0 AND visitor_count >= 0 AND buyer_count >= 0', name='ck_commerce_daily_metrics_counts_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_daily_metrics_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'stat_date', 'granularity', name='uq_commerce_daily_metrics_connection_date_granularity')
    )
    op.create_index('ix_commerce_daily_metrics_date', 'commerce_daily_metrics', ['stat_date'], unique=False)
    op.create_table('commerce_event_inbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_event_inbox_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('external_subject_id', sa.String(length=255), nullable=False),
    sa.Column('event_id_scope', sa.Enum('provider', 'subject', name='ck_commerce_event_inbox_event_id_scope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('external_entity_id', sa.String(length=255), nullable=True),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sanitized_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('routing_status', sa.Enum('pending', 'routed', 'unroutable_subject', 'ambiguous_subject', name='ck_commerce_event_inbox_routing_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('processing_status', sa.Enum('received', 'queued', 'processing', 'succeeded', 'failed', 'ignored', name='ck_commerce_event_inbox_processing_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('routed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('last_error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint('length(dedupe_key) = 64', name='ck_commerce_event_inbox_dedupe_key_length'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_event_inbox_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_commerce_event_inbox_dedupe_key')
    )
    op.create_index('ix_commerce_event_inbox_processing', 'commerce_event_inbox', ['processing_status', 'received_at'], unique=False)
    op.create_index('ix_commerce_event_inbox_subject', 'commerce_event_inbox', ['provider', 'external_subject_id'], unique=False)
    op.create_table('commerce_inventory_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_sku_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_inventory_snapshots_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint('quantity >= 0 AND (available_quantity IS NULL OR available_quantity >= 0)', name='ck_commerce_inventory_quantities_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_inventory_snapshots_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_sku_id', 'captured_at', name='uq_commerce_inventory_connection_sku_captured')
    )
    op.create_index('ix_commerce_inventory_captured_at', 'commerce_inventory_snapshots', ['captured_at'], unique=False)
    op.create_table('commerce_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_item_id', sa.String(length=255), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('external_product_id', sa.String(length=255), nullable=True),
    sa.Column('external_sku_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_order_items_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_order_items_currency_format'),
    sa.CheckConstraint('quantity > 0 AND unit_amount >= 0 AND paid_amount >= 0', name='ck_commerce_order_items_amounts_and_quantity'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_order_items_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_item_id', name='uq_commerce_order_items_connection_external_item')
    )
    op.create_index('ix_commerce_order_items_order', 'commerce_order_items', ['connection_id', 'external_order_id'], unique=False)
    op.create_table('commerce_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('external_shop_id', sa.String(length=255), nullable=True),
    sa.Column('normalized_status', sa.Enum('unknown', 'pending_payment', 'paid', 'shipped', 'completed', 'closed', name='ck_commerce_orders_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('buyer_digest', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('shipping_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_orders_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_orders_currency_format'),
    sa.CheckConstraint('length(buyer_digest) = 64', name='ck_commerce_orders_buyer_digest_length'),
    sa.CheckConstraint('order_amount >= 0 AND paid_amount >= 0 AND discount_amount >= 0 AND shipping_amount >= 0', name='ck_commerce_orders_amounts_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_orders_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_order_id', name='uq_commerce_orders_connection_external_order')
    )
    op.create_index('ix_commerce_orders_status', 'commerce_orders', ['normalized_status', 'ordered_at'], unique=False)
    op.create_table('commerce_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_product_id', sa.String(length=255), nullable=False),
    sa.Column('external_shop_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'on_sale', 'off_shelf', 'deleted', name='ck_commerce_products_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_products_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_products_currency_format'),
    sa.CheckConstraint('price IS NULL OR price >= 0', name='ck_commerce_products_price_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_products_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_product_id', name='uq_commerce_products_connection_external_product')
    )
    op.create_index('ix_commerce_products_provider_status', 'commerce_products', ['provider', 'normalized_status'], unique=False)
    op.create_table('commerce_refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_refund_id', sa.String(length=255), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('external_item_id', sa.String(length=255), nullable=True),
    sa.Column('normalized_status', sa.Enum('unknown', 'requested', 'processing', 'approved', 'rejected', 'completed', 'closed', name='ck_commerce_refunds_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason_code', sa.String(length=255), nullable=True),
    sa.Column('refund_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refund_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_refunds_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_refunds_currency_format'),
    sa.CheckConstraint('amount >= 0', name='ck_commerce_refunds_amount_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_refunds_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_refund_id', name='uq_commerce_refunds_connection_external_refund')
    )
    op.create_index('ix_commerce_refunds_order', 'commerce_refunds', ['connection_id', 'external_order_id'], unique=False)
    op.create_index('ix_commerce_refunds_status', 'commerce_refunds', ['normalized_status'], unique=False)
    op.create_table('commerce_settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_settlement_id', sa.String(length=255), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=True),
    sa.Column('normalized_status', sa.Enum('unknown', 'pending', 'settled', 'reversed', name='ck_commerce_settlements_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_settlements_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_settlements_currency_format'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_settlements_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_settlement_id', name='uq_commerce_settlements_connection_external_settlement')
    )
    op.create_index('ix_commerce_settlements_date', 'commerce_settlements', ['settlement_date'], unique=False)
    op.create_table('commerce_shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_shipment_id', sa.String(length=255), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'pending', 'shipped', 'in_transit', 'delivered', 'returned', 'cancelled', name='ck_commerce_shipments_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('carrier_code', sa.String(length=255), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_shipments_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_shipments_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_shipment_id', name='uq_commerce_shipments_connection_external_shipment')
    )
    op.create_index('ix_commerce_shipments_order', 'commerce_shipments', ['connection_id', 'external_order_id'], unique=False)
    op.create_index('ix_commerce_shipments_status', 'commerce_shipments', ['normalized_status'], unique=False)
    op.create_table('commerce_shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_shop_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'active', 'inactive', 'closed', name='ck_commerce_shops_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_shops_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_shops_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_shop_id', name='uq_commerce_shops_connection_external_shop')
    )
    op.create_index('ix_commerce_shops_provider_status', 'commerce_shops', ['provider', 'normalized_status'], unique=False)
    op.create_table('commerce_skus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_sku_id', sa.String(length=255), nullable=False),
    sa.Column('external_product_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('normalized_status', sa.Enum('unknown', 'on_sale', 'off_shelf', 'deleted', name='ck_commerce_skus_normalized_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('raw_status', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('platform_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('platform_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_commerce_skus_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.CheckConstraint("length(currency) = 3 AND substr(currency, 1, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 2, 1) BETWEEN 'A' AND 'Z' AND substr(currency, 3, 1) BETWEEN 'A' AND 'Z'", name='ck_commerce_skus_currency_format'),
    sa.CheckConstraint('price IS NULL OR price >= 0', name='ck_commerce_skus_price_nonnegative'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_commerce_skus_connection_provider', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_sku_id', name='uq_commerce_skus_connection_external_sku')
    )
    op.create_index('ix_commerce_skus_product', 'commerce_skus', ['connection_id', 'external_product_id'], unique=False)
    op.create_table('integration_sync_checkpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('shops', 'products', 'skus', 'inventory', 'orders', 'order_items', 'refunds', 'shipments', 'settlements', 'daily_metrics', 'ad_accounts', 'ad_entities', 'ad_daily_metrics', 'ad_balance_snapshots', 'ad_finance_transactions', name='ck_integration_sync_checkpoints_resource_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cursor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('watermark_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'retry_wait', 'complete', 'failed', name='ck_integration_sync_checkpoints_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_integration_sync_checkpoints_attempts_nonnegative'),
    sa.CheckConstraint('window_end > window_start', name='ck_integration_sync_checkpoints_window'),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], name='fk_integration_sync_checkpoints_connection', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'resource_type', 'window_start', 'window_end', name='uq_integration_sync_checkpoints_connection_resource_window')
    )
    op.create_index('ix_integration_sync_checkpoints_due', 'integration_sync_checkpoints', ['status', 'next_retry_at'], unique=False)
    op.create_index('ix_integration_sync_checkpoints_lease_expires_at', 'integration_sync_checkpoints', ['lease_expires_at'], unique=False)
    op.create_table('commerce_product_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commerce_product_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('linked_by_session_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(linked_by_session_digest) = 64', name='ck_commerce_product_links_linked_by_session_digest_length'),
    sa.ForeignKeyConstraint(['commerce_product_id'], ['commerce_products.id'], name='fk_commerce_product_links_commerce_product', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_commerce_product_links_product', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commerce_product_id', name='uq_commerce_product_links_commerce_product')
    )
    op.create_index('ix_commerce_product_links_product_id', 'commerce_product_links', ['product_id'], unique=False)
    op.create_table('integration_sync_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('scheduled', 'manual', 'event', 'backfill', 'retry', name='ck_integration_sync_runs_source', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'retry_wait', 'succeeded', 'partial_success', 'failed', 'cancelled', name='ck_integration_sync_runs_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('resource_type', sa.Enum('shops', 'products', 'skus', 'inventory', 'orders', 'order_items', 'refunds', 'shipments', 'settlements', 'daily_metrics', 'ad_accounts', 'ad_entities', 'ad_daily_metrics', 'ad_balance_snapshots', 'ad_finance_transactions', name='ck_integration_sync_runs_resource_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_quarantined', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name='ck_integration_sync_runs_progress'),
    sa.CheckConstraint('records_read >= 0 AND records_written >= 0 AND records_skipped >= 0 AND records_quarantined >= 0', name='ck_integration_sync_runs_counts_nonnegative'),
    sa.CheckConstraint('window_end > window_start', name='ck_integration_sync_runs_window'),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['integration_sync_checkpoints.id'], name='fk_integration_sync_runs_checkpoint', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['integration_sync_runs.id'], name='fk_integration_sync_runs_parent', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_sync_runs_checkpoint', 'integration_sync_runs', ['checkpoint_id', 'started_at'], unique=False)
    op.create_index('ix_integration_sync_runs_status', 'integration_sync_runs', ['status', 'started_at'], unique=False)
    op.create_table('integration_archive_manifests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('qianchuan', 'doudian', 'taobao', 'pdd', name='ck_integration_archive_manifests_provider', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('shops', 'products', 'skus', 'inventory', 'orders', 'order_items', 'refunds', 'shipments', 'settlements', 'daily_metrics', 'ad_accounts', 'ad_entities', 'ad_daily_metrics', 'ad_balance_snapshots', 'ad_finance_transactions', name='ck_integration_archive_manifests_resource_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relative_path', sa.String(length=2048), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(sha256) = 64', name='ck_integration_archive_manifests_sha256_length'),
    sa.CheckConstraint('page_number >= 0 AND record_count >= 0', name='ck_integration_archive_manifests_counts_nonnegative'),
    sa.CheckConstraint('window_end > window_start', name='ck_integration_archive_manifests_window'),
    sa.ForeignKeyConstraint(['connection_id', 'provider'], ['integration_connections.id', 'integration_connections.provider'], name='fk_integration_archive_manifests_connection_provider', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['integration_sync_runs.id'], name='fk_integration_archive_manifests_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path', name='uq_integration_archive_manifests_relative_path'),
    sa.UniqueConstraint('run_id', 'page_number', name='uq_integration_archive_manifests_run_page')
    )
    op.create_index('ix_integration_archive_manifests_connection', 'integration_archive_manifests', ['connection_id'], unique=False)
    op.create_index('ix_integration_archive_manifests_expires_at', 'integration_archive_manifests', ['expires_at'], unique=False)
    op.create_table('integration_sync_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('external_key_hmac', sa.String(length=64), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('sanitized_summary', sa.Text(), nullable=True),
    sa.Column('field_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(external_key_hmac) = 64', name='ck_integration_sync_errors_external_key_hmac_length'),
    sa.ForeignKeyConstraint(['run_id'], ['integration_sync_runs.id'], name='fk_integration_sync_errors_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_integration_sync_errors_run_id', 'integration_sync_errors', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_integration_sync_errors_run_id', table_name='integration_sync_errors')
    op.drop_table('integration_sync_errors')
    op.drop_index('ix_integration_archive_manifests_expires_at', table_name='integration_archive_manifests')
    op.drop_index('ix_integration_archive_manifests_connection', table_name='integration_archive_manifests')
    op.drop_table('integration_archive_manifests')
    op.drop_index('ix_integration_sync_runs_status', table_name='integration_sync_runs')
    op.drop_index('ix_integration_sync_runs_checkpoint', table_name='integration_sync_runs')
    op.drop_table('integration_sync_runs')
    op.drop_index('ix_commerce_product_links_product_id', table_name='commerce_product_links')
    op.drop_table('commerce_product_links')
    op.drop_index('ix_integration_sync_checkpoints_lease_expires_at', table_name='integration_sync_checkpoints')
    op.drop_index('ix_integration_sync_checkpoints_due', table_name='integration_sync_checkpoints')
    op.drop_table('integration_sync_checkpoints')
    op.drop_index('ix_commerce_skus_product', table_name='commerce_skus')
    op.drop_table('commerce_skus')
    op.drop_index('ix_commerce_shops_provider_status', table_name='commerce_shops')
    op.drop_table('commerce_shops')
    op.drop_index('ix_commerce_shipments_status', table_name='commerce_shipments')
    op.drop_index('ix_commerce_shipments_order', table_name='commerce_shipments')
    op.drop_table('commerce_shipments')
    op.drop_index('ix_commerce_settlements_date', table_name='commerce_settlements')
    op.drop_table('commerce_settlements')
    op.drop_index('ix_commerce_refunds_status', table_name='commerce_refunds')
    op.drop_index('ix_commerce_refunds_order', table_name='commerce_refunds')
    op.drop_table('commerce_refunds')
    op.drop_index('ix_commerce_products_provider_status', table_name='commerce_products')
    op.drop_table('commerce_products')
    op.drop_index('ix_commerce_orders_status', table_name='commerce_orders')
    op.drop_table('commerce_orders')
    op.drop_index('ix_commerce_order_items_order', table_name='commerce_order_items')
    op.drop_table('commerce_order_items')
    op.drop_index('ix_commerce_inventory_captured_at', table_name='commerce_inventory_snapshots')
    op.drop_table('commerce_inventory_snapshots')
    op.drop_index('ix_commerce_event_inbox_subject', table_name='commerce_event_inbox')
    op.drop_index('ix_commerce_event_inbox_processing', table_name='commerce_event_inbox')
    op.drop_table('commerce_event_inbox')
    op.drop_index('ix_commerce_daily_metrics_date', table_name='commerce_daily_metrics')
    op.drop_table('commerce_daily_metrics')
    op.drop_index('ix_commerce_ad_finance_transaction_at', table_name='commerce_ad_finance_transactions')
    op.drop_table('commerce_ad_finance_transactions')
    op.drop_index('ix_commerce_ad_entities_status', table_name='commerce_ad_entities')
    op.drop_index('ix_commerce_ad_entities_parent', table_name='commerce_ad_entities')
    op.drop_table('commerce_ad_entities')
    op.drop_index('ix_commerce_ad_daily_metrics_date', table_name='commerce_ad_daily_metrics')
    op.drop_table('commerce_ad_daily_metrics')
    op.drop_index('ix_commerce_ad_balance_snapshots_captured_at', table_name='commerce_ad_balance_snapshots')
    op.drop_table('commerce_ad_balance_snapshots')
    op.drop_index('ix_commerce_ad_accounts_status', table_name='commerce_ad_accounts')
    op.drop_table('commerce_ad_accounts')
    op.drop_index('ix_integration_worker_heartbeats_last_seen_at', table_name='integration_worker_heartbeats')
    op.drop_table('integration_worker_heartbeats')
    op.drop_index('ix_integration_jobs_lease_expires_at', table_name='integration_jobs')
    op.drop_index('ix_integration_jobs_claim', table_name='integration_jobs')
    op.drop_table('integration_jobs')
    op.drop_index('ix_integration_export_jobs_status', table_name='integration_export_jobs')
    op.drop_index('ix_integration_export_jobs_requester_session_digest', table_name='integration_export_jobs')
    op.drop_index('ix_integration_export_jobs_expires_at', table_name='integration_export_jobs')
    op.drop_table('integration_export_jobs')
    # Drop the referenced ownership key only after every dependent table is gone.
    op.drop_constraint('uq_integration_connections_id_provider', 'integration_connections', type_='unique')
    # ### end Alembic commands ###
