"""Seedance 2.0 storyboard prompt generation."""
from __future__ import annotations

from pathlib import Path
import re
from typing import Any

from services.ai_config import get_or_create_interface_setting, resolve_interface_connection
from services.ai_service import ai_service


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SKILL_PATH = REPO_ROOT / "skills" / "seedance-2-0-prompt" / "SKILL.md"
SEEDANCE_INTERFACE_KEY = "seedance_prompt"
MAX_AUTO_SCENES = 24
BRACKET_RE = re.compile(r"[（(]([^（）()]{1,140})[）)]")
TALKING_HEAD_KEYWORDS = ("口播", "主播", "出镜", "真人", "面对镜头", "对镜", "讲解", "边说")
TALKING_HEAD_PATTERNS = (re.compile(r"拿着.{0,40}说"),)
SEEDANCE_CONFIG_UNAVAILABLE_DETAIL = "Seedance 分镜提示词生成接口未配置，请检查 AI 配置后重试。"
SEEDANCE_CALL_FAILED_DETAIL = "Seedance 分镜提示词生成接口不可用或调用失败，请检查 AI 配置后重试。"
SEEDANCE_EMPTY_OUTPUT_DETAIL = "Seedance 分镜提示词生成接口未返回可解析的分镜提示词，请重试。"
SEEDANCE_COUNT_MISMATCH_DETAIL = "Seedance 分镜提示词生成接口返回的分镜数量与脚本断句不一致，请重试。"


class SeedancePromptGenerationError(Exception):
    """Raised when Seedance prompts cannot be generated by the configured AI."""

    def __init__(self, status_code: int, detail: str):
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


class SeedancePromptGenerator:
    """Generate copy-ready Seedance 2.0 prompts from a script."""

    def __init__(self, ai=None, skill_path: str | Path | None = None):
        self.ai = ai or ai_service
        self.skill_path = Path(skill_path) if skill_path else DEFAULT_SKILL_PATH

    async def generate(
        self,
        *,
        script_content: str,
        requirements: str | None = None,
        db=None,
    ) -> dict[str, Any]:
        script = (script_content or "").strip()
        beats = self._extract_beats(script, MAX_AUTO_SCENES)
        target_count = max(1, len(beats))
        messages = self._build_messages(script, requirements, beats)
        self._ensure_ai_configured(db)

        try:
            content = await self.ai.chat(
                messages,
                temperature=0.7,
                interface_key=SEEDANCE_INTERFACE_KEY,
                allow_fallback=False,
                db=db,
            )
        except Exception as exc:
            raise SeedancePromptGenerationError(
                503,
                SEEDANCE_CALL_FAILED_DETAIL,
            ) from exc

        parsed = self._parse_prompt_text(content, MAX_AUTO_SCENES)
        if not parsed:
            raise SeedancePromptGenerationError(
                502,
                SEEDANCE_EMPTY_OUTPUT_DETAIL,
            )
        if len(parsed) != target_count:
            raise SeedancePromptGenerationError(
                502,
                SEEDANCE_COUNT_MISMATCH_DETAIL,
            )
        self._attach_script_labels(parsed, beats)
        return {
            "prompt_text": self._format_prompt_text(parsed),
            "items": parsed,
            "source": "ai",
        }

    def _ensure_ai_configured(self, db=None) -> None:
        if db is None:
            return
        try:
            setting = get_or_create_interface_setting(db, SEEDANCE_INTERFACE_KEY)
            connection = resolve_interface_connection(setting)
        except Exception as exc:
            raise SeedancePromptGenerationError(
                503,
                SEEDANCE_CONFIG_UNAVAILABLE_DETAIL,
            ) from exc
        if not connection.get("configured"):
            raise SeedancePromptGenerationError(
                503,
                SEEDANCE_CONFIG_UNAVAILABLE_DETAIL,
            )

    def _build_messages(
        self,
        script: str,
        requirements: str | None,
        beats: list[dict[str, str]],
    ) -> list[dict[str, str]]:
        skill = self._load_skill()
        beat_lines = "\n".join(self._format_beat_line(index, beat) for index, beat in enumerate(beats, start=1))
        user_prompt = (
            "请把用户脚本转换成 Seedance 2.0 可直接复制的视频分镜提示词。\n"
            "- 按脚本断句，为每个有效句子生成 1 个画面提示词，不能要求用户选择分镜数量。\n"
            "- 每个句子生成 1 个独立可复制的画面提示词；如果句子超过 24 个，只处理下方句子清单中的前 24 个。\n"
            "- 优先选择最能证明产品、动作、质地、包装或成品结果的镜头。\n"
            "- 每个画面独立可复制，必须遵守技能里的 9:16、真实商业短视频、无字幕/水印/虚假文字等约束。\n"
            "- 括号内文字是画面初稿/拍摄说明，必须以它为基础扩写成完整 Seedance 画面提示词。\n"
            "- 括号外文字只用于理解产品、动作、卖点和表达节奏，不要写成字幕或画面里的文字。\n"
            "- 如果没有括号画面说明，则按句号、问号、感叹号、换行等自然断句并由AI推断画面。\n"
            "- 输出格式必须严格为：画面1：提示词，然后空行，画面2：提示词。\n"
        )
        if requirements:
            user_prompt += f"\n用户需求：{requirements.strip()}\n"
        if beat_lines:
            user_prompt += f"\n已按脚本断句得到的句子清单：\n{beat_lines}\n"
        user_prompt += f"\n用户脚本：\n{script}"
        return [
            {"role": "system", "content": skill},
            {"role": "user", "content": user_prompt},
        ]

    def _format_beat_line(self, index: int, beat: dict[str, str]) -> str:
        lines = [
            f"{index}. 画面初稿：{beat['scene'] or '由AI根据口播推断'}",
            f"   口播/上下文：{beat['line'] or '无'}",
        ]
        if self._is_talking_head_beat(beat):
            lines.extend([
                "   视频类型：真人口播带货视频",
                "   口播要求：真人主播入镜，自然对镜讲解，手持/指向/展示产品，真实烘焙门店或干净台面，无字幕/水印/虚假文字。",
            ])
        return "\n".join(lines)

    def _is_talking_head_beat(self, beat: dict[str, str]) -> bool:
        scene = (beat.get("scene") or "").strip()
        parts = [beat.get("line") or ""]
        if scene and scene != "口播画面":
            parts.append(scene)
        text = " ".join(parts)
        return any(keyword in text for keyword in TALKING_HEAD_KEYWORDS) or any(
            pattern.search(text) for pattern in TALKING_HEAD_PATTERNS
        )

    def _load_skill(self) -> str:
        try:
            return self.skill_path.read_text(encoding="utf-8-sig").strip()
        except OSError:
            return (
                "# Seedance 2.0 Prompt\n"
                "Create concise Chinese vertical 9:16 commercial video prompts. "
                "No captions, no subtitles, no watermark, no fake text."
            )

    def _parse_prompt_text(self, text: str | None, limit: int) -> list[dict[str, Any]]:
        cleaned = self._clean_ai_text(text)
        if not cleaned:
            return []

        pattern = re.compile(r"(?:^|\n)\s*画面\s*(\d+)\s*[：:]\s*(.*?)(?=\n\s*画面\s*\d+\s*[：:]|\Z)", re.S)
        items: list[dict[str, Any]] = []
        for index, match in enumerate(pattern.finditer(cleaned), start=1):
            prompt = self._compact_prompt(match.group(2))
            if not prompt:
                continue
            items.append({
                "scene_number": index,
                "label": self._label_from_prompt(prompt),
                "prompt": prompt,
            })
            if len(items) >= limit:
                break

        if items:
            return items
        return []

    def _clean_ai_text(self, text: str | None) -> str:
        value = (text or "").strip()
        value = re.sub(r"^```(?:text|markdown)?\s*", "", value, flags=re.I)
        value = re.sub(r"\s*```$", "", value)
        return value.strip()

    def _compact_prompt(self, text: str) -> str:
        value = re.sub(r"\s+", " ", (text or "").replace("\x00", " ")).strip()
        value = re.sub(r"^[\-*•·]\s*", "", value)
        return value

    def _label_from_prompt(self, prompt: str) -> str:
        text = re.sub(r"^[，。；：、,.!?！？\s]+", "", prompt or "").strip()
        text = re.split(r"[。；;，,]", text, maxsplit=1)[0].strip()
        return (text or "Seedance 画面")[:54]

    def _attach_script_labels(self, items: list[dict[str, Any]], beats: list[dict[str, str]]) -> None:
        for index, item in enumerate(items):
            if index >= len(beats):
                continue
            item["label"] = self._label_from_beat(beats[index]) or item.get("label") or "Seedance 画面"

    def _label_from_beat(self, beat: dict[str, str]) -> str:
        line = self._label_from_script_text(beat.get("line") or "")
        if line:
            return line
        scene = beat.get("scene") or ""
        if scene and scene != "口播画面":
            return self._label_from_script_text(scene)
        return "Seedance 画面"

    def _label_from_script_text(self, text: str) -> str:
        value = re.sub(r"\s+", " ", (text or "").replace("\x00", " ")).strip()
        value = re.sub(r"^[，。；：、,.!?！？\s]+|[，。；：、,.!?！？\s]+$", "", value)
        return value[:54]

    def _format_prompt_text(self, items: list[dict[str, Any]]) -> str:
        return "\n\n".join(f"画面{item['scene_number']}：{item['prompt']}" for item in items)

    def _extract_beats(self, script: str, limit: int) -> list[dict[str, str]]:
        text = (script or "").strip()
        beats: list[dict[str, str]] = []

        for line in self._script_lines(text):
            for beat in self._extract_line_beats(line):
                beats.append(beat)
                if len(beats) >= limit:
                    return beats
        if beats:
            return beats
        return [{"scene": "口播画面", "line": text}] if text else []

    def _script_lines(self, text: str) -> list[str]:
        return [line.strip() for line in re.split(r"(?:\r?\n)+", text or "") if line.strip()]

    def _extract_line_beats(self, line: str) -> list[dict[str, str]]:
        matches = list(BRACKET_RE.finditer(line))
        if not matches:
            return [{"scene": "口播画面", "line": part} for part in self._split_sentences(line)]

        first_match = matches[0]
        if not line[:first_match.start()].strip():
            return self._extract_leading_scene_line(line, matches)
        return self._extract_trailing_scene_line(line, matches)

    def _extract_leading_scene_line(self, line: str, matches: list[re.Match]) -> list[dict[str, str]]:
        beats: list[dict[str, str]] = []
        for index, match in enumerate(matches):
            scene = match.group(1).strip()
            next_start = matches[index + 1].start() if index + 1 < len(matches) else len(line)
            spoken_block = line[match.end():next_start].strip()
            parts = self._split_sentences(spoken_block) or [""]
            for part in parts:
                beats.append({"scene": scene, "line": part})
        return beats

    def _extract_trailing_scene_line(self, line: str, matches: list[re.Match]) -> list[dict[str, str]]:
        beats: list[dict[str, str]] = []
        cursor = 0
        last_spoken = ""
        for match in matches:
            scene = match.group(1).strip()
            spoken_block = line[cursor:match.start()].strip()
            parts = self._split_sentences(spoken_block)
            if parts:
                for part in parts[:-1]:
                    beats.append({"scene": "口播画面", "line": part})
                last_spoken = parts[-1]
                paired_line = last_spoken
            else:
                paired_line = last_spoken
            beats.append({"scene": scene, "line": paired_line})
            cursor = match.end()

        tail = line[cursor:].strip()
        for part in self._split_sentences(tail):
            beats.append({"scene": "口播画面", "line": part})
        return beats

    def _split_sentences(self, text: str) -> list[str]:
        cleaned = (text or "").replace("\x00", " ").replace("\r\n", "\n").replace("\r", "\n")
        cleaned = re.sub(r"[ \t\f\v]+", " ", cleaned).strip()
        if not cleaned:
            return []
        parts = [part.strip() for part in re.split(r"(?:\r?\n)+|(?<=[。！？!?；;])\s*", cleaned) if part.strip()]
        if len(parts) <= 1 and len(cleaned) > 160:
            parts = [part.strip() for part in re.split(r"(?<=[，,、])\s*", cleaned) if part.strip()]
        return parts or [cleaned]

seedance_prompt_generator = SeedancePromptGenerator()
